- name: nginx install and run
  hosts: nginx
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: yes    



- name: mysql and run
  hosts: mysql
  tasks:
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: run mysql
    ansible.builtin.systemd:
      name: mysql
      state: started
      enabled: yes    