- name: nginx install and run
  hosts: nginx
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: yes    