- name: nginx
  hosts: 192.168.74.135
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enable: yes    