- name: print the varibles
  hosts: nginx
  vars_prompt:
  - name: course
    prompt: please enter course
  - name: duration
    prompt: please enter course 
  - name: trainer
    prompt: please enter trainer 
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "hi iam learning {{course}}, duration: {{duration}}, trainer is: {{trainer}}"