- name: print the varibles
  hosts: nginx
  vars_files:
  - vars.yaml
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "hi iam learning {{course}}, duration: {{duration}}, trainer is: {{trainer}}"