- name: datatypes in ansible
  hosts: local
  connection: local
  vars:
  course: "devops with aws"
  duration: 120
  topics:
  - linux
  - shell
  - ansible
  live: true
  tools:
   ci: jennkins
   cm: ansible
   cloud: aws
   aws:
   - s3
   - iam
  tasks:
  - name: print course
    ansible.builtin.debug:
      msg: " hi iam learning {{course}}, duration: {{duration}}, topics are: {{topics}}, live: {{live}}, tols are:{{tools}}," 