- name: check a number
  hosts: web
  connection: local
  vars_prompt:
  - name: my_number
    prompt: please enter the number
  tasks: 
  - name: print the number
    ansible.builtin.debug:
      msg: "Given is {{my_number}} is less then 10"
    when: my_number | int < 10  