- name: create user
  hosts: local
  connection: local
  tasks: 
  - name: check user
    ansible.builtin.command: id expense
    register: user
    ignore_errors: True

  - name: print user
    ansible.builtin.debug:
      msg: "USER IS {{ user }}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: user.rc != 0