- name: install packages using loop
  hosts: all
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    
  - name: start and run
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes


    loop:
    - postfix
    - mysql
    - httpd
    - vsftpd
